[terminal]
shell = { program = "zsh", args = ["-l"] }

[general]
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]
#import = ["~/.config/alacritty/themes/gruvbox_light.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"
duration = 0

[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Beam"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 16.0

[font.bold]
family = "Iosevka SS05"
style = "Bold"

[font.bold_italic]
family = "Iosevka SS05"
style = "Bold Italic"

[font.italic]
family = "Iosevka SS05"
style = "Italic"

[font.normal]
family = "Iosevka SS05"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
decorations = "None"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 1
#opacity = 0.95
startup_mode = "Maximized"
title = "Alacritty"

[keyboard]
bindings = [
{ key = "Insert", mods = "Control", action = "Copy" },
{ key = "Insert", mods = "Shift", action = "Paste" },
]
